### ISSUE TITLE
Feature Request: Sonarr and Radarr Integration

### ISSUE THREAD

**Issue by jaretclifton** [HH0718/PyTulli#2]
Instead of having the files deleted directly from this script, call the APIs for Sonarr and/or Radarr to have those items removed and marked as unmonitored (or remove the Sonarr/Radarr item completely) to prevent the items from being re-downloaded automatically.

**Comment by HH0718** [comment]
Not a bad idea. I'll consider integrating Radarr.
Thanks for your input.

**Comment by HH0718** [comment]
Updated PyTulli to 2.0 to integrate Radarr. This version does exactly what you recommended in your original comment. Thanks for the suggestion.

Sonarr will be next, followed by Ombi.
